### ISSUE TITLE
BTC-EUR pair support

### ISSUE THREAD

**Issue by dymex0** [VertigoRay/GDAXBot#10]
Just a suggestion - EU users cannot trade on BTC-USD.

**Comment by rverhe** [comment]
Hello Dymex0, same issue here. Do you solved it by yourself yet?

**Comment by ghost** [comment]
Try ack-grep on ubuntu to find the instances of BTC-USD and replace with your preferred currency.

Lazy way is to do it through here: https://github.com/VertigoRay/GDAXBot/search?utf8=%E2%9C%93&q=BTC-USD&type=
