### ISSUE TITLE
Failing on 0.1.3

### ISSUE THREAD

**Issue by ghost** [VertigoRay/GDAXBot#4]
~/GDAXBot-0.1.3$ npm start

> gdax-trader@0.1.3 start /home/jacobcmcqueen/GDAXBot-0.1.3
> node . 

/home/jacobcmcqueen/GDAXBot-0.1.3/main.js:206
}, terminal_data.coins;
                 ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 4.9.0-3-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gdax-trader@0.1.3 start: `node . `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gdax-trader@0.1.3 start script 'node . '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gdax-trader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node . 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gdax-trader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gdax-trader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jacobcmcqueen/GDAXBot-0.1.3/npm-debug.log

**Comment by VertigoRay** [comment]
Pretty sure I fixed that with #3; just wanted to re-pull and test before tagging the release.

**Comment by VertigoRay** [comment]
Try `0.1.4` and let me know. :)
