### ISSUE TITLE
n_trades in config twice under BTC_USD

### ISSUE THREAD

**Issue by ghost** [VertigoRay/GDAXBot#5]
:) pretty self explanatory
n_trades in config twice under BTC_USD
check default.yaml

Saw that it was fixed in master, but exists in 1.4 release.

Just wanted to note this, but system is running.

**Comment by VertigoRay** [comment]
Made the change available in [0.1.5](https://github.com/VertigoRay/GDAXBot/releases/tag/0.1.5)
